### ISSUE TITLE
Missing CodeBlock component

### ISSUE THREAD

**Issue by thegurf** [octahedroid/gatsbyconf#1]
Thanks so much for the gatsbyconf demo and walkthrough last week Jesus.

In working through the README.md, I ran into a glitch with section 5.B. It seems that it's referencing a file that doesn't exist:

`import ParagraphCodeBlock from "../components/paragraph/paragraph-code-block";`

Any chance you could check that file in so we can see how that component works?

**Comment by jmolivas** [comment]
@thegurf glad you like it

done I push the missing commit including that file 
https://github.com/octahedroid/gatsbyconf/blob/main/src/components/paragraph/paragraph-code-block.js

**Comment by thegurf** [comment]
Thanks much!
